FROM openjdk:22-jdk-slim

# Maintaner data 
LABEL maintainer="andre philipe <andre.apg@gmail.com>"

COPY ./target/percept-2.6.3.war /app/percept-2.6.3.war
WORKDIR /app

# Build the application with Maven
#RUN mvn package

# Expose default Spring Boot port
EXPOSE 8081

# Run the jar file

ENTRYPOINT ["java", "-jar", "percept-2.6.3.war"]

#End